name: Deploy Website to GitHub Pages

on:
  push:
    branches:
      - patch-1  # Deploy on push to the patch-1 branch

permissions:
  contents: write  # Allow write access to contents, which includes pushing to gh-pages
  pages: write     # Allow write access to GitHub Pages

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Install Jekyll and dependencies (if needed)
    - name: Set up Ruby and Jekyll
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1'  # Specify the Ruby version if you need it

    - name: Install dependencies
      run: |
        gem install jekyll bundler
        bundle install

    # Step 3: Build the Jekyll site (if you're using Jekyll or another static site generator)
    - name: Build the Website
      run: |
        bundle exec jekyll build

    # Step 4: Deploy to GitHub Pages
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site  # Set to the _site directory where Jekyll outputs the built site