name: Deploy Website to GitHub Pages

on:
  push:
    branches:
      - patch-1  # Deploy on push to the patch-1 branch

permissions:
  contents: write  # Allow write access to contents, which includes pushing to gh-pages
  pages: write     # Allow write access to GitHub Pages

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Build the site (uncomment and modify if needed)
    # If your site requires a build step (e.g., for static site generators like Jekyll or React)
    # Uncomment and modify this section
    #- name: Install Dependencies
    #  run: npm install

    #- name: Build the Website
    #  run: npm run build

    # Step 3: Deploy to GitHub Pages
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./  # Set to root directory